apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techradar-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: techradar.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: techradar-web
                port:
                  number: 80
