apiVersion: v1
kind: Service
metadata:
  name: techradar-web
  labels:
    app: techradar-web
spec:
  type: ClusterIP
  selector:
    app: techradar-web
  ports:
    - name: http
      port: 80
      targetPort: 80
